// <auto-generated />
namespace pegatronb2b.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sku : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sku));
        
        string IMigrationMetadata.Id
        {
            get { return "201605120627114_sku"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
