// <auto-generated />
namespace pegatronb2b.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class comp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comp));
        
        string IMigrationMetadata.Id
        {
            get { return "201605030703048_comp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
